# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: KBOGraph - Update data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * 3-10 *' # 매일 자정에 실행

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: KBO Scraper with python
      run: |
        python "kbo_scrapper.py"
    - name: League simulation with python
      run: |
        python "cwp_simulator.py" -p 16 --game_path 'data/completed_games.pkl' --probability_path 'data/uniform_probability.pkl' --standing_path 'data/standing.pkl' --comingup_path 'data/comingup_games.pkl' --cli_path 'data/li.pkl' --probability_output 'data/uniform_probability.pkl' --standing_output 'data/standing.pkl' --cli_output 'data/li.pkl'
        python "cwp_simulator.py" -p 16 --game_path 'data/completed_games.pkl' --probability_path 'data/log5_probability.pkl' --standing_path 'data/standing.pkl' --probability_output 'data/log5_probability.pkl' --standing_output 'data/standing.pkl' --winratio 'data/win_setting/2024_log5.pkl'
        python "cwp_simulator.py" -p 16 --game_path 'data/completed_games.pkl' --probability_path 'data/pythagorean_probability.pkl' --standing_path 'data/standing.pkl' --probability_output 'data/pythagorean_probability.pkl' --standing_output 'data/standing.pkl' --winratio 'pythagorean'
    - name: Preprocess for deployment
      run: |
        python "preprocess_deploy.py"
    - name: Commits
      run: |
        git config --local user.email "sooo@novelmaterial@gmail.com"
        git config --local user.name "Sooo Kim" # 커밋에 포함될 이름
        git add ./data
        git add ./fig
        if [[ ! `git status --porcelain` ]]; then exit 0; fi
        git commit -m "Auto: `date +'%Y-%m-%d'`"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'master'
        github_token: $
